### ISSUE TITLE
expose `sass_option_set_c_functions`

### ISSUE THREAD

**Issue by septs** [bep/golibsass#7]
expose `sass_option_set_c_functions` api on hugo

allow hugo define hugo-specific built-in sass functions

for example:

```scss
$site-param-value: hugo.param("key"); // equal by `index .Site.Params "key"`

.example {
  background-image: hugo.get-match("logo**");

  @each $image in hugo.match("images/**.png") {
    [name="#{path.basename($image)}"]::before {
      background-image: $image;
    }
  }
}
```

https://github.com/bep/golibsass/blob/55e726fd7d7d0ce2ddf2fe85e2c1116e09f01e25/libsass_src/include/sass/context.h#L109

https://github.com/bep/golibsass/blob/55e726fd7d7d0ce2ddf2fe85e2c1116e09f01e25/libsass_src/src/sass_context.hpp#L59-L60

see https://sass-lang.com/documentation/values/maps
see https://sass-lang.com/documentation/values/lists
